### Spring properties
# Service registers under this name
spring:
  application:
    name: emp-service
# Discovery Server Access
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 2222

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false