#server.port=5555
#spring.application.name=zuul-server
#eureka.instance.preferIpAddress=true
#eureka.client.registerWithEureka=true
#eureka.client.fetchRegistry=true
#eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka
server:
  port: 5555
spring:
  application:
    name: zuul-gate
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
zuul:
  prefix: /api
    routes:
      emp:
        path: /empl/**
          serviceId: http://10.140.225.14:2222/emps/1